version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  sistema_cache:
    image: redis:latest
    container_name: cache
    command: redis-server --maxmemory 15M --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"

  generador_respuestas:
    build: ./response_gen
    container_name: cerebro_flask
    depends_on:
      - kafka
      - sistema_cache
    ports:
      - "5005:5000"
    volumes:
      - ./data:/app/data

  generador_trafico:
    build: ./traffic_gen
    container_name: atacante_trafico
    depends_on:
      - kafka
      - generador_respuestas

  trabajador_1:
    build: ./consumers
    container_name: consumer_worker_1
    depends_on:
      - kafka
      - generador_respuestas